### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Bondifrench** [klipspringr/blpapi-react#1]
Hi,

I would like to emulate your example app with a different framework (Mithril.js) but first I would like to make yours run.

I have Bloomberg installed on my computer, and I am a subscriber.
First: just a comment: to launch server.js `Express` and `body-parser` are missing from the dependencies in `package.json`

Second: Once I installed everything and was logged into Bloomberg, I tried to make it run and I had a connection refused.
To test the connection I tried to use curl as indicated [here](https://github.com/bloomberg/blpapi-http/blob/develop/examples/shell/ReferenceData.sh) when using your React example, do we need also certificates and keys?

Thanks

**Comment by teresaibarra** [comment]
Hey! I was never notified of this, how weird.

If you're still interested, I can take a look @Bondifrench

**Comment by Bondifrench** [comment]
haha As BBG is not really helpful for using their API and you have probably moved on, thought you could not reply.
I manage to connect to my BBG server on local, using [blpapi-node](https://github.com/bloomberg/blpapi-node) however reading your code I can not see you opening a `session` you seem to be directly making POST requests, would be interested to understand better how you link your React App to the BBG on a local machine.

**Comment by teresaibarra** [comment]
This was one of my first programming projects ever! It's definitely rough to come back to it. 

Most of your questions, if I remember correctly, were handled by my mentor back during my internship, @ericlu88. It seems like he's actually still working at Bloomberg, but possibly not on the same team. I don't know if I could be of any more help in terms of connecting to the API, but I'm happy to help you reach out to those who could.
